service: notes-yard-backend

useDotenv: true

plugins: 
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  environment: 
    NOTEBOOKS_TABLE: "UserNotebooks"
    PASTEBIN_TABLE: "UserPasteBins"
    SWOTBOARD_TABLE: "UserSwotBoards"
    NOTES_TABLE: "UserNotes"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ["arn:aws:dynamodb:ap-south-1:318066470757:table/UserSwotBoards","arn:aws:dynamodb:ap-south-1:318066470757:table/UserPasteBins", "arn:aws:dynamodb:ap-south-1:318066470757:table/UserNotes", "arn:aws:dynamodb:ap-south-1:318066470757:table/UserNotebooks"]

functions:
  notebook:
    handler: Notebook/index.handler
    package:
      individually: true
      artifact: "./dist/Notebook.zip"
    cors: true
    events:
      - http:
          path: notebook
          method: post
          cors: true
      - http:
          path: notebook
          method: get
          cors: true
      - http:
            path: notebook/{notebookId}
            method: put
            cors: true
      - http:
          path: notebook/{notebookId}
          method: delete
          cors: true
  pasteBin:
    handler: PasteBin/index.handler
    package:
      individually: true
      artifact: "./dist/PasteBin.zip"
    cors: true
    events:
      - http:
          path: pasteBin
          method: post
          cors: true
      - http:
          path: pasteBin/{pasteBinId}
          method: get
          cors: true
    
      